[project]
name = "HelloXilos"
version = "0.1.0"
description = "This is a test project for Xilos"
authors = ["Milosz Bertman <milosz.bertman@gmail.com>"]
readme = "README.md"
package_name = "xilos_pkg"

[cloud]
# Provider options: "gcp", "aws", "azure"
provider = "gcp"

[repository]
# Type options: "github", "gitlab", "bitbucket"
type = "github"

[monitor]
numeric_threshold = 0.05
numerical = "wasserstein"
categorical = "psi"
